/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cbt_app;

import java.io.BufferedReader;
import java.io.FileReader;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author telol
 */
public class lecturer_homepage extends javax.swing.JFrame {

    /**
     * Creates new form lecturer_homepage
     */
    public lecturer_homepage() {
        initComponents();
        get_scores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    void get_scores()
    
    {
        DefaultTableModel tb = (DefaultTableModel)scoreTable.getModel();
        while(tb.getRowCount()!= 0)
        {
        tb.removeRow(0);
        }
      try{
        Class.forName("com.mysql.cj.jdbc.Driver"); //connects to the driver
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cbt_db", "root", "tomiolasoji"); //makes the driver conncet to
            PreparedStatement ps = con.prepareStatement("SELECT * FROM score");
         
        ResultSet rs =    ps.executeQuery();
        while(rs.next())
        {
            String[] rowData = new String[2];
       rowData[0] =  rs.getString("mat_no");
        rowData[1] = rs.getString("score");
        tb.addRow(rowData);
        }
        }catch(Exception e){
            e.printStackTrace();}
    
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jComboBox3 = new javax.swing.JComboBox<>();
        jFileChooser1 = new javax.swing.JFileChooser();
        lecturer_jframe = new javax.swing.JTabbedPane();
        register_students = new javax.swing.JPanel();
        bulk_reg = new javax.swing.JButton();
        indi_reg = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        FirstNameTF = new javax.swing.JTextField();
        SurnameTF = new javax.swing.JTextField();
        OtherNameTF = new javax.swing.JTextField();
        Search = new javax.swing.JButton();
        modify = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        MatNoTF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        EmialTF = new javax.swing.JTextField();
        delete = new javax.swing.JButton();
        questions = new javax.swing.JPanel();
        Clear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        QuestionTF = new javax.swing.JTextField();
        optionATF = new javax.swing.JTextField();
        optionBTF = new javax.swing.JTextField();
        enter = new javax.swing.JButton();
        optionCTF = new javax.swing.JTextField();
        Delete = new javax.swing.JButton();
        optionDTF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        browse = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        correct_ans = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        questionNumTF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        timeOfTestTF = new javax.swing.JTextField();
        set_questions = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        scoreTable = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bulk_reg.setText("Bulk Registration");
        bulk_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bulk_regActionPerformed(evt);
            }
        });

        indi_reg.setText("Individual Registration");
        indi_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indi_regActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout register_studentsLayout = new javax.swing.GroupLayout(register_students);
        register_students.setLayout(register_studentsLayout);
        register_studentsLayout.setHorizontalGroup(
            register_studentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(register_studentsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(register_studentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bulk_reg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(indi_reg, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE))
                .addContainerGap(537, Short.MAX_VALUE))
        );
        register_studentsLayout.setVerticalGroup(
            register_studentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(register_studentsLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(bulk_reg)
                .addGap(29, 29, 29)
                .addComponent(indi_reg)
                .addContainerGap(491, Short.MAX_VALUE))
        );

        lecturer_jframe.addTab(" Register students", register_students);

        jLabel1.setText("First Name");

        jLabel2.setText("Surname");

        jLabel3.setText("Other name");

        jLabel4.setText("Gender");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Female");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Male");

        jLabel5.setText("Department");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select depratment", "Computer Science", "Software engineering", "Mechanical Engineering", "Electrical Engineering", " " }));

        jLabel6.setText(" Level");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select level", "100L", "200L", "300L", "400L", "500L", " " }));

        OtherNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OtherNameTFActionPerformed(evt);
            }
        });

        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        modify.setText("Modify ");
        modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyActionPerformed(evt);
            }
        });

        jLabel8.setText("Mat no.");

        MatNoTF.setText("type student mat_no to search");
        MatNoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MatNoTFActionPerformed(evt);
            }
        });

        jLabel9.setText("Email");

        EmialTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmialTFActionPerformed(evt);
            }
        });

        delete.setText("Delete record");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FirstNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(40, 40, 40)
                        .addComponent(MatNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(OtherNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SurnameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(43, 43, 43)
                        .addComponent(jRadioButton1)
                        .addGap(69, 69, 69)
                        .addComponent(jRadioButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EmialTF, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(Search)
                .addGap(44, 44, 44)
                .addComponent(modify)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 415, Short.MAX_VALUE)
                .addComponent(delete)
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(MatNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(FirstNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OtherNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SurnameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(EmialTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Search)
                    .addComponent(modify)
                    .addComponent(delete))
                .addGap(69, 69, 69))
        );

        lecturer_jframe.addTab("view student records", jPanel1);

        Clear.setText("Clear all");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Question", "Option A", "Option B", "Option C", "Option D", "Correct answer"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        QuestionTF.setText("Enter Question ");
        QuestionTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuestionTFActionPerformed(evt);
            }
        });
        QuestionTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                QuestionTFKeyTyped(evt);
            }
        });

        optionATF.setText("Enter Option A");
        optionATF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionATFActionPerformed(evt);
            }
        });

        optionBTF.setText("Enter Option B");

        enter.setText("Enter");
        enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterActionPerformed(evt);
            }
        });

        optionCTF.setText("Enter Option C");
        optionCTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionCTFActionPerformed(evt);
            }
        });

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        optionDTF.setText("Enter Option D");
        optionDTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionDTFActionPerformed(evt);
            }
        });

        jButton1.setText("Upload");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setText(" ");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        browse.setText("Browse");
        browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseActionPerformed(evt);
            }
        });

        jLabel16.setText("Select File");

        correct_ans.setText("Correct Answer");

        jLabel7.setText("Number of test questions:");

        questionNumTF.setText(" ");

        jLabel10.setText("mins");

        jLabel11.setText("Duration of test:");

        timeOfTestTF.setText(" ");

        set_questions.setText("Set test parameters");
        set_questions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set_questionsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout questionsLayout = new javax.swing.GroupLayout(questions);
        questions.setLayout(questionsLayout);
        questionsLayout.setHorizontalGroup(
            questionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionsLayout.createSequentialGroup()
                .addGroup(questionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(questionsLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(browse))
                    .addGroup(questionsLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(questionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(questionsLayout.createSequentialGroup()
                                .addGroup(questionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(questionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(optionCTF)
                                        .addComponent(optionATF)
                                        .addComponent(QuestionTF, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addComponent(optionBTF)
                                        .addComponent(optionDTF))
                                    .addComponent(correct_ans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1))
                            .addGroup(questionsLayout.createSequentialGroup()
                                .addGroup(questionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(questionsLayout.createSequentialGroup()
                                        .addComponent(enter)
                                        .addGap(76, 76, 76)
                                        .addComponent(jButton1)
                                        .addGap(18, 18, 18)
                                        .addComponent(Clear)
                                        .addGap(27, 27, 27)
                                        .addComponent(Delete))
                                    .addGroup(questionsLayout.createSequentialGroup()
                                        .addGroup(questionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(questionsLayout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(questionNumTF, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(questionsLayout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addGap(57, 57, 57)
                                                .addComponent(timeOfTestTF, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel10)))
                                .addGap(0, 332, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(questionsLayout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(set_questions)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        questionsLayout.setVerticalGroup(
            questionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionsLayout.createSequentialGroup()
                .addGroup(questionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(questionsLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(QuestionTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(optionATF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(optionBTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(optionCTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(optionDTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(correct_ans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(questionsLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(questionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(browse)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(questionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enter)
                    .addComponent(Clear)
                    .addComponent(Delete)
                    .addComponent(jButton1))
                .addGap(51, 51, 51)
                .addGroup(questionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(questionNumTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(questionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(timeOfTestTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(set_questions)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lecturer_jframe.addTab("Set Test", questions);

        scoreTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matriculation number", "Score"
            }
        ));
        jScrollPane2.setViewportView(scoreTable);

        jButton2.setText("Refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        lecturer_jframe.addTab("view students scores", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lecturer_jframe, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lecturer_jframe, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void browseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseActionPerformed
        FileNameExtensionFilter filter = new FileNameExtensionFilter("CSV files", "csv");
        jFileChooser1.setAcceptAllFileFilterUsed(false);
        jFileChooser1.addChoosableFileFilter(filter);
        int open = jFileChooser1.showOpenDialog(null);
        if (open != jFileChooser1.APPROVE_OPTION) {
            return;
        } else {
            String filename = jFileChooser1.getSelectedFile().getAbsolutePath().toString();
            String file = jFileChooser1.getSelectedFile().getName().toString();
            jTextField1.setText(filename);
            if (!filename.contains(".csv")) {
                filename = filename + ".csv";
            }
            try {
                String line;
                DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
                BufferedReader br = new BufferedReader(new FileReader(jFileChooser1.getSelectedFile()));
                while ((line = br.readLine()) != null) {
                    String[] data = line.split(",");
                    tableModel.addRow(data);
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Error reading file");
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_browseActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
            String insertQuery = "INSERT INTO questions values (?,?,?,?,?,?)";
            Class.forName("com.mysql.cj.jdbc.Driver"); //connects to the driver
            String path = "jdbc:mysql://localhost:3306/cbt_db";
            String root = "root";
            String pass = "tomiolasoji";
            Connection con = DriverManager.getConnection(path, root, pass);
            PreparedStatement ps = con.prepareStatement(insertQuery);

            for (int row = 0; row < jTable1.getRowCount(); row++) {
                for (int col = 0; col < jTable1.getColumnCount(); col++) {
                    Object value = jTable1.getValueAt(row, col);
                    ps.setObject(col+1, value);
                }

                ps.executeUpdate();
            }

            JOptionPane.showMessageDialog(rootPane, "Record inserted");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void optionDTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionDTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optionDTFActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        try {//delete from database
            String value = (String) jTable1.getValueAt(jTable1.getSelectedRow(), jTable1.getSelectedColumn());

            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cbt_db", "root", "tomiolasoji");
            PreparedStatement ps = con.prepareStatement("DELETE FROM questions WHERE questions=?");
            ps.setString(1, value);
            int rs = ps.executeUpdate();

            JOptionPane.showMessageDialog(rootPane, "Record deleted");

            //delete from entry point
            QuestionTF.setText("");
            optionATF.setText("");
            optionBTF.setText("");
            optionCTF.setText("");
            optionDTF.setText("");
            correct_ans.setText("");

            //delete row in table
            DefaultTableModel table = (DefaultTableModel) jTable1.getModel();
            int row = jTable1.getSelectedRow();
            table.removeRow(row);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);}

    }//GEN-LAST:event_DeleteActionPerformed

    private void optionCTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionCTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optionCTFActionPerformed

    private void enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterActionPerformed
        String question = QuestionTF.getText();
        String option_a = optionATF.getText();
        String option_b = optionBTF.getText();
        String option_c = optionCTF.getText();
        String option_d = optionDTF.getText();
        String correct= correct_ans.getText();

        String data[] = {question, option_a, option_b, option_c, option_d,correct};
        DefaultTableModel td = (DefaultTableModel) jTable1.getModel();
        td.addRow(data);
    }//GEN-LAST:event_enterActionPerformed

    private void optionATFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionATFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optionATFActionPerformed

    private void QuestionTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QuestionTFKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_QuestionTFKeyTyped

    private void QuestionTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuestionTFActionPerformed
        QuestionTF.setText("");   // TODO add your handling code here:
    }//GEN-LAST:event_QuestionTFActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        DefaultTableModel td = (DefaultTableModel) jTable1.getModel();
        td.setRowCount(0);
    }//GEN-LAST:event_ClearActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        try {
            String matno = MatNoTF.getText();

            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cbt_db", "root", "tomiolasoji");
            PreparedStatement ps = con.prepareStatement("DELETE FROM student WHERE mat_no=?");
            ps.setString(1, matno);
            int rs = ps.executeUpdate();

            JOptionPane.showMessageDialog(rootPane, "Record deleted");

            MatNoTF.setText("");
            FirstNameTF.setText("");
            SurnameTF.setText("");
            OtherNameTF.setText("");
            EmialTF.setText("");
            buttonGroup1.clearSelection();
            jComboBox1.setSelectedIndex(0); //department field
            jComboBox2.setSelectedIndex(0);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }  // TODO add your handling code here:
    }//GEN-LAST:event_deleteActionPerformed

    private void EmialTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmialTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmialTFActionPerformed

    private void MatNoTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MatNoTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MatNoTFActionPerformed

    private void modifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyActionPerformed
        try {
            String matno = MatNoTF.getText();
            String firstName = FirstNameTF.getText();
            String surName = SurnameTF.getText();
            String middleName = OtherNameTF.getText();
            String email = EmialTF.getText();
            String gender = null;

            if (jRadioButton1.isSelected()) {
                gender = "Female";
            } else if (jRadioButton2.isSelected()) {
                gender = "Male";
            }

            String department = (String) jComboBox1.getSelectedItem();
            String level = jComboBox2.getSelectedItem().toString(); //the above is a differnt way to change to string

            Class.forName("com.mysql.cj.jdbc.Driver"); //connects to the driver
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cbt_db", "root", "tomiolasoji"); //makes the driver conncet to
            PreparedStatement ps = con.prepareStatement("UPDATE student SET first_name = ?, middle_name=?, last_name=?, level=?, department=?, gender=?, email=? WHERE mat_no=? ");
            ps.setString(1, firstName);
            ps.setString(2, middleName);
            ps.setString(3, surName);
            ps.setString(4, level);
            ps.setString(5, department);
            ps.setString(6, gender);
            ps.setString(7, email);
            ps.setString(8, matno);

            int rs = ps.executeUpdate();

            JOptionPane.showMessageDialog(rootPane, "Record updated");

            MatNoTF.setText("");
            FirstNameTF.setText("");
            SurnameTF.setText("");
            OtherNameTF.setText("");
            EmialTF.setText("");
            buttonGroup1.clearSelection();
            jComboBox1.setSelectedIndex(0); //department field
            jComboBox2.setSelectedIndex(0);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_modifyActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        try {
            String matno = MatNoTF.getText();

            if (matno.equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Enter ID");
            } else {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cbt_db", "root", "tomiolasoji");
                PreparedStatement ps = con.prepareStatement("SELECT * FROM student WHERE mat_no=?");

                ps.setString(1, matno);
                ResultSet rs = ps.executeQuery();
                while (rs.next()) {
                    FirstNameTF.setText(rs.getString(2));
                    OtherNameTF.setText(rs.getString(3));
                    SurnameTF.setText(rs.getString(5));
                    EmialTF.setText(rs.getString(8));
                    String gender = rs.getString(7);
                    String department = rs.getString(6);
                    String level = rs.getString(5);

                    //set gender
                    if (gender.equalsIgnoreCase("Female")) {
                        jRadioButton1.setSelected(true);
                    } else {
                        jRadioButton2.setSelected(true);
                    }
                    //set departemnt
                    if (department.equalsIgnoreCase("Computer Science")) {
                        jComboBox1.setSelectedIndex(1);
                    } else if (department.equalsIgnoreCase("Software engineering")) {
                        jComboBox1.setSelectedIndex(2);
                    } else if (department.equalsIgnoreCase("Mechanical engineering")) {
                        jComboBox1.setSelectedIndex(3);
                    } else if (department.equalsIgnoreCase("Electricakl engineering")) {
                        jComboBox1.setSelectedIndex(4);
                    } else {
                        jComboBox1.setSelectedIndex(0);
                    }
                    //set level
                    if (level.equalsIgnoreCase("100L")) {
                        jComboBox2.setSelectedIndex(1);
                    } else if (level.equalsIgnoreCase("200L")) {
                        jComboBox2.setSelectedIndex(2);
                    } else if (level.equalsIgnoreCase("300L")) {
                        jComboBox2.setSelectedIndex(3);
                    } else if (level.equalsIgnoreCase("400L")) {
                        jComboBox2.setSelectedIndex(4);
                    } else if (level.equalsIgnoreCase("500L")) {
                        jComboBox2.setSelectedIndex(5);
                    } else {
                        jComboBox2.setSelectedIndex(0);
                    }

                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_SearchActionPerformed

    private void OtherNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OtherNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OtherNameTFActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void indi_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indi_regActionPerformed
        setVisible(false);
        new indivi_reg().setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_indi_regActionPerformed

    private void bulk_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bulk_regActionPerformed
        setVisible(false);
        new bulk_registration().setVisible(true);
    }//GEN-LAST:event_bulk_regActionPerformed

    private void set_questionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set_questionsActionPerformed
    String no_questions = questionNumTF.getText();
    String test_time = timeOfTestTF.getText();
    
     try {
            
            String insertQuery = "INSERT INTO test_layout values (?,?)";
            Class.forName("com.mysql.cj.jdbc.Driver"); //connects to the driver
            String path = "jdbc:mysql://localhost:3306/cbt_db";
            String root = "root";
            String pass = "tomiolasoji";
            Connection con = DriverManager.getConnection(path, root, pass);
            PreparedStatement ps = con.prepareStatement(insertQuery);
            
            ps.setString(1, no_questions);
            ps.setString(2,test_time);
            int rs = ps.executeUpdate();
           
            JOptionPane.showMessageDialog(rootPane,  "inserted");
            
            questionNumTF.setText("");
            timeOfTestTF.setText("");
            

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }   
    // TODO add your handling code here:
    }//GEN-LAST:event_set_questionsActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    get_scores();    // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lecturer_homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lecturer_homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lecturer_homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lecturer_homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lecturer_homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JButton Delete;
    private javax.swing.JTextField EmialTF;
    private javax.swing.JTextField FirstNameTF;
    private javax.swing.JTextField MatNoTF;
    private javax.swing.JTextField OtherNameTF;
    private javax.swing.JTextField QuestionTF;
    private javax.swing.JButton Search;
    private javax.swing.JTextField SurnameTF;
    private javax.swing.JButton browse;
    private javax.swing.JButton bulk_reg;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField correct_ans;
    private javax.swing.JButton delete;
    private javax.swing.JButton enter;
    private javax.swing.JButton indi_reg;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTabbedPane lecturer_jframe;
    private javax.swing.JButton modify;
    private javax.swing.JTextField optionATF;
    private javax.swing.JTextField optionBTF;
    private javax.swing.JTextField optionCTF;
    private javax.swing.JTextField optionDTF;
    private javax.swing.JTextField questionNumTF;
    private javax.swing.JPanel questions;
    private javax.swing.JPanel register_students;
    private javax.swing.JTable scoreTable;
    private javax.swing.JButton set_questions;
    private javax.swing.JTextField timeOfTestTF;
    // End of variables declaration//GEN-END:variables
}
